apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/accounts-dpl.yaml
      - ./infra/k8s/events-dpl.yaml
      - ./infra/k8s/gateway-dpl.yaml
      - ./infra/k8s/nats-dpl.yaml
build:
  local:
    push: false
  artifacts:
    - image: asolerp/accounts
      context: services/accounts
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: asolerp/events
      context: services/events
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: asolerp/gateway
      context: apigetaway/gateway
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
        