apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./services/manifests/accounts-mongo-dpl.yml
      - ./services/manifests/accounts-dpl.yml
      - ./apigetaway/manifests/gateway-dpl.yml
build:
  local:
    push: false
  artifacts:
    - image: asolerp/accounts
      context: services/accounts
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
    - image: asolerp/gateway
      context: apigetaway/gateway
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
        