kind: Deployment
apiVersion: apps/v1
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      initContainers:
        - name: wait-gateway
          image: busybox:1.30.0
          command: ['sh', '-c', 'sleep 30']
      containers:
        - name: gateway
          image: asolerp/gateway:latest

---
kind: Service
apiVersion: v1
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  ports:
    - port: 4000
      nodePort: 30000
  type: NodePort
