apiVersion: v1
kind: ConfigMap
metadata:
  name: prisma-configmap
  labels:
    name: prisma-accounts
    app: prisma-accounts
data:
  PRISMA_CONFIG: |
    port: 4466
    databases:
      default:
        connector: mongo
        uri: mongodb://mongo-accounts:27017/accounts

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prisma-accounts
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: prisma-accounts
  template:
    metadata:
      labels:
        app: prisma-accounts
    spec:
      containers:
        - name: prisma-accounts
          image: 'prismagraphql/prisma:1.34.10'
          ports:
            - name: prisma-accounts
              containerPort: 4466
          env:
            - name: PRISMA_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: prisma-configmap
                  key: PRISMA_CONFIG

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: accounts
spec:
  selector:
    matchLabels:
      app: accounts
  replicas: 1
  template:
    metadata:
      labels:
        app: accounts
    spec:
      containers:
        - name: accounts
          image: asolerp/accounts:latest
          env:
            - name: PRISMA_URL
              value: "http://prisma-accounts:4466/accounts/dev"

---
kind: Service
apiVersion: v1
metadata:
  name: accounts
spec:
  selector:
    app: accounts
  ports:
    - port: 4001
  type: ClusterIP


---
kind: Service
apiVersion: v1
metadata:
  name: prisma-accounts
spec:
  selector:
    app: prisma-accounts
  ports:
    - port: 4466
  type: ClusterIP
