apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts-mongo
  template:
    metadata:
      labels:
        app: accounts-mongo
    spec:
      containers:
        - name: accounts-mongo
          image: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: accounts-mongo
spec:
  selector:
    app: accounts-mongo
  ports:
    - port: 27017
      nodePort: 30001
  type: NodePort