apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: prisma-accounts
  name: prisma-accounts
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: prisma-accounts
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: prisma-accounts
    spec:
      containers:
      - env:
        - name: PRISMA_CONFIG
          value: |
            port: 4466
            # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
            # managementApiSecret: my-secret
            databases:
              default:
                connector: mongo
                uri: 'mongodb+srv://admin:Ayc.051213@federation.i80y9.mongodb.net/federation?retryWrites=true&w=majority'
        image: prismagraphql/prisma:1.34
        imagePullPolicy: ""
        name: prisma-accounts
        ports:
        - containerPort: 4466
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: accounts
  name: accounts
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: accounts
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: accounts
    spec:
      containers:
      - env:
        - name: NATS_CLIEND_ID
          value: accounts-nats
        - name: NATS_CLUSTER_ID
          value: federation
        - name: NATS_URL
          value: http://nats-srv:4222
        - name: PRISMA_URL
          value: http://prisma-accounts:4466/accounts/dev
        image: asolerp/accounts
        imagePullPolicy: ""
        name: accounts
        ports:
        - containerPort: 4001
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: accounts
  name: accounts
spec:
  ports:
  - name: "4001"
    port: 4001
    targetPort: 4001
  selector:
    io.kompose.service: accounts
status:
  loadBalancer: {}

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: prisma-accounts
  name: prisma-accounts
spec:
  ports:
  - name: "4466"
    port: 4466
    targetPort: 4466
  selector:
    io.kompose.service: prisma-accounts
status:
  loadBalancer: {}
