apiVersion: v1
kind: ConfigMap
metadata:
  name: prisma-configmap
  labels:
    name: prisma-events
    app: prisma-events
data:
  PRISMA_CONFIG: |
    port: 4467
    databases:
      default:
        connector: mongo
        uri: mongodb+srv://admin:Ayc.051213@federation.i80y9.mongodb.net/federation?retryWrites=true&w=majority

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prisma-events
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: prisma-events
  template:
    metadata:
      labels:
        app: prisma-events
    spec:
      containers:
        - name: prisma-events
          image: 'prismagraphql/prisma:1.34.10'
          ports:
            - name: prisma-events
              containerPort: 4467
          env:
            - name: PRISMA_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: prisma-configmap
                  key: PRISMA_CONFIG

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: events
spec:
  selector:
    matchLabels:
      app: events
  replicas: 1
  template:
    metadata:
      labels:
        app: events
    spec:
      containers:
        - name: events
          image: asolerp/events:latest
          env:
            - name: NATS_CLIEND_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: federation
            - name: PRISMA_URL
              value: "http://prisma-events:4467/events/dev"

---
kind: Service
apiVersion: v1
metadata:
  name: events
spec:
  selector:
    app: events
  ports:
    - port: 4002
  type: ClusterIP


---
kind: Service
apiVersion: v1
metadata:
  name: prisma-events
spec:
  selector:
    app: prisma-events
  ports:
    - port: 4467
  type: ClusterIP
