apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: matches
  name: matches
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: matches
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: matches
    spec:
      containers:
      - env:
        - name: MONGO_URI
          value: mongodb+srv://admin:Ayc.051213@federation.i80y9.mongodb.net/matches_dev?retryWrites=true&w=majority 
        - name: NATS_CLIEND_ID
          value: matches-nats
        - name: NATS_CLUSTER_ID
          value: federation
        - name: NATS_URL
          value: http://nats-srv:4222
        - name: PRISMA_URL
          value: http://prisma-matches:4467/matches/dev
        image: asolerp/matches
        imagePullPolicy: ""
        name: matches
        ports:
        - containerPort: 4002
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: matches
  name: matches
spec:
  ports:
  - name: "4002"
    port: 4002
    targetPort: 4002
  selector:
    io.kompose.service: matches
status:
  loadBalancer: {}

  
  