apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: phone-verification
  name: phone-verification
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: phone-verification
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: phone-verification
    spec:
      containers:
      - env:
        - name: MONGO_URI
          value: mongodb+srv://admin:Ayc.051213@federation.i80y9.mongodb.net/phone-verification_dev?retryWrites=true&w=majority 
        - name: NATS_CLIEND_ID
          value: phone-verification-nats
        - name: NATS_CLUSTER_ID
          value: federation
        - name: NATS_URL
          value: http://nats-srv:4222
        image: asolerp/phone-verification
        imagePullPolicy: ""
        name: phone-verification
        ports:
        - containerPort: 4003
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: phone-verification
  name: phone-verification
spec:
  ports:
  - name: "4003"
    port: 4003
    targetPort: 4003
  selector:
    io.kompose.service: phone-verification
status:
  loadBalancer: {}

  
  